### ISSUE TITLE
#源码更新问题#

### ISSUE THREAD

**Issue by iT-lijun** [ant-motion/ant-v-landing-page#1]
**0. 问题描述**
[Ant-V官网效果](https://antv.alipay.com/zh-cn/index.html)与 源码**ant-v-landing-page**不一致哟！
**1. 我的建议**
Ant-V官网效果做的很**赞**很**awesome**！ 期待您可以**push最新**的ant-v-landing-page**源码**至gitHub！

**Comment by jljsj33** [comment]
只有导航与页尾不一样，，这里的导航和页尾是我后面新加上去的。。有些内容我在 landings 里肯定要去掉或重构的。。。

**Comment by yaoshanliang** [comment]
![image](https://user-images.githubusercontent.com/5028569/61358342-afdf5080-a8ac-11e9-812f-67889d23ee3c.png)

这个很棒 会更新到这种效果嘛

**Comment by jljsj33** [comment]
这是个 video。。。
